sys: {
  label: Evolution of Natural Systems
  env: {
    label: Randomness / Influence of the Gods
  }
  other_sys: {
    label: More Primitive Evolved Systems
  }
  abs: {
    label: Fuzzy Abstraction\n(Evolved Natural System)
    shape: cloud
  }
  env2: {
    label: Natural Environment
  }
  env -> abs: produces
  abs -> env2: acts on
  env2 -> abs: influenced by/\nbuilt from
  other_sys -> env: blend with
}
