sys: {
  label: Evolved Engineered Systems
  arch: {
    label: Engineered architecture
  }
  inp: {
    label: System input
  }
  evo: {
    label: Evolution algorithm
  }
  abs: {
    label: Vague fuzzy learned abstraction
    shape: cloud
  }
  out {
    label: System output
  }
  arch -> abs
  inp -> abs
  abs -> out
  evo -> abs
}
