system: {
  label: A Natural System
  axioms: {
    label: Unknowable / Incomplete Axioms
  }
  env: {
    label: Environment
  }
  obs: {
    label: Observations / Facts / Truths
  }
  axioms -> env: {
    label: Act on
    style.font-size: 20
  }
  env -> obs: {
    label: Produces
    style.font-size: 20
  }
}
