from dataclasses import dataclass
import polars as pl

product_type: pl.Enum = pl.Enum(
    [
        "Mobile CPU",
        "Laptop CPU",
        "Desktop CPU",
        "Server CPU",
        "Discrete GPU",
        "AI Accelerator",
    ]
)


@dataclass
class Product:
    name: str
    year: int
    product_type: str
    transistor_count: int
    manufacturer: str
    show: bool = False
    dx: int = 0
    dy: int = 25


product_list: list[Product] = [
    # Product(
    #     name="MP944 (20-bit, 6-chip, 28 chips total)",
    #     year=1970,
    #     product_type="Desktop CPU",
    #     transistor_count=74442,
    #     manufacturer="Garrett AiResearch",
    # ),
    Product(
        name="Intel 4004",
        year=1971,
        product_type="Desktop CPU",
        transistor_count=2250,
        manufacturer="Intel",
        show=True,
        dx=10,
        dy=20,
    ),
    Product(
        name="TMX 1795 (8-bit, 24-pin)",
        year=1971,
        product_type="Desktop CPU",
        transistor_count=3078,
        manufacturer="Texas Instruments",
    ),
    Product(
        name="Intel 8008 (8-bit, 18-pin)",
        year=1972,
        product_type="Desktop CPU",
        transistor_count=3500,
        manufacturer="Intel",
    ),
    Product(
        name="NEC μCOM-4 (4-bit, 42-pin)",
        year=1973,
        product_type="Mobile CPU",
        transistor_count=2500,
        manufacturer="NEC",
    ),
    Product(
        name="Toshiba TLCS-12 (12-bit)",
        year=1973,
        product_type="Mobile CPU",
        transistor_count=11000,
        manufacturer="Toshiba",
    ),
    Product(
        name="Intel 4040 (4-bit, 16-pin)",
        year=1974,
        product_type="Desktop CPU",
        transistor_count=3000,
        manufacturer="Intel",
    ),
    Product(
        name="Motorola 6800 (8-bit, 40-pin)",
        year=1974,
        product_type="Desktop CPU",
        transistor_count=4100,
        manufacturer="Motorola",
    ),
    Product(
        name="Intel 8080 (8-bit, 40-pin)",
        year=1974,
        product_type="Desktop CPU",
        transistor_count=6000,
        manufacturer="Intel",
    ),
    Product(
        name="TMS 1000 (4-bit, 28-pin)",
        year=1974,
        product_type="Mobile CPU",
        transistor_count=8000,
        manufacturer="Texas Instruments",
    ),
    Product(
        name="MOS Technology 6502 (8-bit, 40-pin)",
        year=1975,
        product_type="Desktop CPU",
        transistor_count=4528,
        manufacturer="MOS Technology",
    ),
    Product(
        name="Intersil IM6100 (12-bit, 40-pin; clone of PDP-8)",
        year=1975,
        product_type="Desktop CPU",
        transistor_count=4000,
        manufacturer="Intersil",
    ),
    Product(
        name="CDP 1801 (8-bit, 2-chip, 40-pin)",
        year=1975,
        product_type="Desktop CPU",
        transistor_count=5000,
        manufacturer="RCA",
    ),
    Product(
        name="RCA 1802 (8-bit, 40-pin)",
        year=1976,
        product_type="Desktop CPU",
        transistor_count=5000,
        manufacturer="RCA",
    ),
    Product(
        name="Zilog Z80 (8-bit, 4-bit ALU, 40-pin)",
        year=1976,
        product_type="Desktop CPU",
        transistor_count=8500,
        manufacturer="Zilog",
    ),
    Product(
        name="Intel 8085 (8-bit, 40-pin)",
        year=1976,
        product_type="Desktop CPU",
        transistor_count=6500,
        manufacturer="Intel",
    ),
    Product(
        name="TMS9900 (16-bit)",
        year=1976,
        product_type="Desktop CPU",
        transistor_count=8000,
        manufacturer="Texas Instruments",
    ),
    Product(
        name="Bellmac-8 (8-bit)",
        year=1977,
        product_type="Desktop CPU",
        transistor_count=7000,
        manufacturer="Bell Labs",
    ),
    Product(
        name="Motorola 6809 (8-bit with some 16-bit features, 40-pin)",
        year=1978,
        product_type="Desktop CPU",
        transistor_count=9000,
        manufacturer="Motorola",
    ),
    Product(
        name="Intel 8086",
        year=1978,
        product_type="Desktop CPU",
        transistor_count=29000,
        manufacturer="Intel",
        show=True,
    ),
    Product(
        name="Zilog Z8000 (16-bit)",
        year=1979,
        product_type="Desktop CPU",
        transistor_count=17500,
        manufacturer="Zilog",
    ),
    Product(
        name="Intel 8088 (16-bit, 8-bit data bus)",
        year=1979,
        product_type="Desktop CPU",
        transistor_count=29000,
        manufacturer="Intel",
    ),
    Product(
        name="Motorola 68000 (16/32-bit, 32-bit registers, 16-bit ALU)",
        year=1979,
        product_type="Desktop CPU",
        transistor_count=68000,
        manufacturer="Motorola",
    ),
    Product(
        name="Intel 8051 (8-bit, 40-pin)",
        year=1980,
        product_type="Mobile CPU",
        transistor_count=50000,
        manufacturer="Intel",
    ),
    Product(
        name="WDC 65C02",
        year=1981,
        product_type="Desktop CPU",
        transistor_count=11500,
        manufacturer="WDC",
    ),
    Product(
        name="ROMP (32-bit)",
        year=1981,
        product_type="Desktop CPU",
        transistor_count=45000,
        manufacturer="IBM",
    ),
    Product(
        name="Intel 80186 (16-bit, 68-pin)",
        year=1982,
        product_type="Desktop CPU",
        transistor_count=55000,
        manufacturer="Intel",
    ),
    Product(
        name="Intel 80286 (16-bit, 68-pin)",
        year=1982,
        product_type="Desktop CPU",
        transistor_count=134000,
        manufacturer="Intel",
    ),
    Product(
        name="WDC 65C816 (8/16-bit)",
        year=1983,
        product_type="Desktop CPU",
        transistor_count=22000,
        manufacturer="WDC",
    ),
    Product(
        name="NEC V20",
        year=1984,
        product_type="Desktop CPU",
        transistor_count=63000,
        manufacturer="NEC",
    ),
    Product(
        name="Motorola 68020 (32-bit; 114 pins used)",
        year=1984,
        product_type="Desktop CPU",
        transistor_count=190000,
        manufacturer="Motorola",
    ),
    Product(
        name="Intel 80386 (32-bit, 132-pin; no cache)",
        year=1985,
        product_type="Desktop CPU",
        transistor_count=275000,
        manufacturer="Intel",
    ),
    Product(
        name="ARM 1",
        year=1985,
        product_type="Mobile CPU",
        transistor_count=25000,
        manufacturer="Acorn",
        show=True,
        dy=45,
    ),
    Product(
        name="Novix NC4016 (16-bit)",
        year=1985,
        product_type="Desktop CPU",
        transistor_count=16000,
        manufacturer="Harris Corporation",
    ),
    Product(
        name="SPARC MB86900 (32-bit; no cache)",
        year=1986,
        product_type="Server CPU",
        transistor_count=110000,
        manufacturer="Fujitsu",
    ),
    Product(
        name="NEC V60 (32-bit; no cache)",
        year=1986,
        product_type="Desktop CPU",
        transistor_count=375000,
        manufacturer="NEC",
    ),
    Product(
        name="ARM 2 (32-bit, 84-pin; no cache)",
        year=1986,
        product_type="Mobile CPU",
        transistor_count=27000,
        manufacturer="Acorn",
    ),
    Product(
        name="Z80000 (32-bit; very small cache)",
        year=1986,
        product_type="Desktop CPU",
        transistor_count=91000,
        manufacturer="Zilog",
    ),
    Product(
        name="NEC V70 (32-bit; no cache)",
        year=1987,
        product_type="Desktop CPU",
        transistor_count=385000,
        manufacturer="NEC",
    ),
    Product(
        name="Hitachi Gmicro/200",
        year=1987,
        product_type="Desktop CPU",
        transistor_count=730000,
        manufacturer="Hitachi",
    ),
    Product(
        name="Motorola 68030 (32-bit, very small caches)",
        year=1987,
        product_type="Desktop CPU",
        transistor_count=273000,
        manufacturer="Motorola",
    ),
    Product(
        name="TI Explorer's 32-bit Lisp machine chip",
        year=1987,
        product_type="Desktop CPU",
        transistor_count=553000,
        manufacturer="Texas Instruments",
    ),
    Product(
        name="DEC WRL MultiTitan",
        year=1988,
        product_type="Desktop CPU",
        transistor_count=180000,
        manufacturer="DEC WRL",
    ),
    Product(
        name="Intel i960 (32-bit, 33-bit memory subsystem, no cache)",
        year=1988,
        product_type="Desktop CPU",
        transistor_count=250000,
        manufacturer="Intel",
    ),
    Product(
        name="Intel i960CA (32-bit, cache)",
        year=1989,
        product_type="Desktop CPU",
        transistor_count=600000,
        manufacturer="Intel",
    ),
    Product(
        name="Intel i860 (32/64-bit, 128-bit SIMD, cache, VLIW)",
        year=1989,
        product_type="Desktop CPU",
        transistor_count=1000000,
        manufacturer="Intel",
    ),
    Product(
        name="Intel 80486 (32-bit, 8 KB cache)",
        year=1989,
        product_type="Desktop CPU",
        transistor_count=1180235,
        manufacturer="Intel",
    ),
    Product(
        name="ARM 3 (32-bit, 4 KB cache)",
        year=1989,
        product_type="Mobile CPU",
        transistor_count=310000,
        manufacturer="Acorn",
    ),
    Product(
        name="POWER1",
        year=1990,
        product_type="Server CPU",
        transistor_count=6900000,
        manufacturer="IBM",
        show=True,
        dx=-3,
    ),
    Product(
        name="Motorola 68040 (32-bit, 8 KB caches)",
        year=1990,
        product_type="Desktop CPU",
        transistor_count=1200000,
        manufacturer="Motorola",
    ),
    Product(
        name="R4000 (64-bit, 16 KB of caches)",
        year=1991,
        product_type="Server CPU",
        transistor_count=1350000,
        manufacturer="MIPS",
    ),
    Product(
        name="ARM 6 (32-bit, no cache for this 60 variant)",
        year=1991,
        product_type="Mobile CPU",
        transistor_count=35000,
        manufacturer="ARM",
    ),
    Product(
        name="Hitachi SH-1 (32-bit, no cache)",
        year=1992,
        product_type="Mobile CPU",
        transistor_count=600000,
        manufacturer="Hitachi",
    ),
    Product(
        name="Intel i960CF (32-bit, cache)",
        year=1992,
        product_type="Desktop CPU",
        transistor_count=900000,
        manufacturer="Intel",
    ),
    Product(
        name="Alpha 21064 (64-bit, 290-pin; 16 KB of caches)",
        year=1992,
        product_type="Server CPU",
        transistor_count=1680000,
        manufacturer="DEC",
    ),
    Product(
        name="Hitachi HARP-1 (32-bit, cache)",
        year=1993,
        product_type="Desktop CPU",
        transistor_count=2800000,
        manufacturer="Hitachi",
    ),
    Product(
        name="Pentium",
        year=1993,
        product_type="Desktop CPU",
        transistor_count=3100000,
        manufacturer="Intel",
        show=True,
        dx=-5,
    ),
    Product(
        name="POWER2 (8-chip module, 288 kB of cache)",
        year=1993,
        product_type="Server CPU",
        transistor_count=23037000,
        manufacturer="IBM",
    ),
    Product(
        name="ARM700 (32-bit; 8 KB cache)",
        year=1994,
        product_type="Mobile CPU",
        transistor_count=578977,
        manufacturer="ARM",
    ),
    Product(
        name="MuP21 (21-bit, 40-pin; includes video)",
        year=1994,
        product_type="Desktop CPU",
        transistor_count=7000,
        manufacturer="Offete Enterprises",
    ),
    Product(
        name="Motorola 68060 (32-bit, 16 KB of caches)",
        year=1994,
        product_type="Desktop CPU",
        transistor_count=2500000,
        manufacturer="Motorola",
    ),
    Product(
        name="PowerPC 601 (32-bit, 32 KB of caches)",
        year=1994,
        product_type="Desktop CPU",
        transistor_count=2800000,
        manufacturer="Apple, IBM, Motorola",
    ),
    Product(
        name="PowerPC 603 (32-bit, 16 KB of caches)",
        year=1994,
        product_type="Desktop CPU",
        transistor_count=1600000,
        manufacturer="Apple, IBM, Motorola",
    ),
    Product(
        name="PowerPC 603e (32-bit, 32 KB of caches)",
        year=1995,
        product_type="Desktop CPU",
        transistor_count=2600000,
        manufacturer="Apple, IBM, Motorola",
    ),
    Product(
        name="Alpha 21164 EV5",
        year=1995,
        product_type="Server CPU",
        transistor_count=9300000,
        manufacturer="DEC",
        show=False,
    ),
    Product(
        name="SA-110 (32-bit, 32 KB of caches)",
        year=1995,
        product_type="Mobile CPU",
        transistor_count=2500000,
        manufacturer="Acorn, DEC, Apple",
    ),
    Product(
        name="Pentium Pro (32-bit, 16 KB of caches; L2 cache on-package, but on separate die)",
        year=1995,
        product_type="Desktop CPU",
        transistor_count=5500000,
        manufacturer="Intel",
    ),
    Product(
        name="PA-8000 64-bit, no cache",
        year=1995,
        product_type="Server CPU",
        transistor_count=3800000,
        manufacturer="HP",
    ),
    Product(
        name="Alpha 21164A EV56 (64-bit, 112 kB cache)",
        year=1996,
        product_type="Server CPU",
        transistor_count=9660000,
        manufacturer="DEC",
    ),
    Product(
        name="K5",  # "AMD K5",
        year=1996,
        product_type="Desktop CPU",
        transistor_count=4300000,
        manufacturer="AMD",
        show=True,
    ),
    Product(
        name="Pentium II Klamath (32-bit, 64-bit SIMD, caches)",
        year=1997,
        product_type="Desktop CPU",
        transistor_count=7500000,
        manufacturer="Intel",
    ),
    Product(
        name="AMD K6 (32-bit, caches)",
        year=1997,
        product_type="Desktop CPU",
        transistor_count=8800000,
        manufacturer="AMD",
    ),
    Product(
        name="F21 (21-bit; includes e.g. video)",
        year=1997,
        product_type="Desktop CPU",
        transistor_count=15000,
        manufacturer="Offete Enterprises",
    ),
    Product(
        name="AVR (8-bit, 40-pin; w/memory)",
        year=1997,
        product_type="Mobile CPU",
        transistor_count=140000,
        manufacturer="Nordic VLSI / Atmel",
    ),
    Product(
        name="Pentium II Deschutes (32-bit, large cache)",
        year=1998,
        product_type="Desktop CPU",
        transistor_count=7500000,
        manufacturer="Intel",
    ),
    Product(
        name="Alpha 21264 EV6 (64-bit)",
        year=1998,
        product_type="Server CPU",
        transistor_count=15200000,
        manufacturer="DEC",
    ),
    Product(
        name="Alpha 21164PC PCA57 (64-bit, 48 kB cache)",
        year=1998,
        product_type="Server CPU",
        transistor_count=5700000,
        manufacturer="Samsung",
    ),
    Product(
        name="Hitachi SH-4 (32-bit, caches)",
        year=1998,
        product_type="Mobile CPU",
        transistor_count=3200000,
        manufacturer="Hitachi",
    ),
    Product(
        name="ARM 9TDMI (32-bit, no cache)",
        year=1999,
        product_type="Mobile CPU",
        transistor_count=111000,
        manufacturer="Acorn",
    ),
    Product(
        name="Pentium III Katmai (32-bit, 128-bit SIMD, caches)",
        year=1999,
        product_type="Desktop CPU",
        transistor_count=9500000,
        manufacturer="Intel",
    ),
    Product(
        name="Emotion Engine (64-bit, 128-bit SIMD, cache)",
        year=1999,
        product_type="Mobile CPU",
        transistor_count=10500000,
        manufacturer="Sony, Toshiba",
    ),
    Product(
        name="Pentium II Mobile Dixon (32-bit, caches)",
        year=1999,
        product_type="Laptop CPU",
        transistor_count=27400000,
        manufacturer="Intel",
    ),
    Product(
        name="AMD K6-III (32-bit, caches)",
        year=1999,
        product_type="Desktop CPU",
        transistor_count=21300000,
        manufacturer="AMD",
    ),
    Product(
        name="AMD K7 (32-bit, caches)",
        year=1999,
        product_type="Desktop CPU",
        transistor_count=22000000,
        manufacturer="AMD",
    ),
    Product(
        name="Gekko (32-bit, large cache)",
        year=2000,
        product_type="Mobile CPU",
        transistor_count=21000000,
        manufacturer="IBM, Nintendo",
    ),
    Product(
        name="Pentium III Coppermine (32-bit, large cache)",
        year=2000,
        product_type="Desktop CPU",
        transistor_count=21000000,
        manufacturer="Intel",
    ),
    Product(
        name="Pentium 4 Willamette",
        year=2000,
        product_type="Desktop CPU",
        transistor_count=42000000,
        manufacturer="Intel",
        show=True,
    ),
    Product(
        name="SPARC64 V (64-bit, large cache)",
        year=2001,
        product_type="Server CPU",
        transistor_count=191000000,
        manufacturer="Fujitsu",
    ),
    Product(
        name="Pentium III Tualatin (32-bit, large cache)",
        year=2001,
        product_type="Desktop CPU",
        transistor_count=45000000,
        manufacturer="Intel",
    ),
    Product(
        name="Pentium 4 Northwood (32-bit, large cache)",
        year=2002,
        product_type="Desktop CPU",
        transistor_count=55000000,
        manufacturer="Intel",
    ),
    Product(
        name="Itanium 2 McKinley (64-bit, large cache)",
        year=2002,
        product_type="Server CPU",
        transistor_count=220000000,
        manufacturer="Intel",
    ),
    Product(
        name="Alpha 21364 (64-bit, 946-pin, SIMD, very large caches)",
        year=2003,
        product_type="Server CPU",
        transistor_count=152000000,
        manufacturer="DEC",
    ),
    Product(
        name="AMD K7 Barton (32-bit, large cache)",
        year=2003,
        product_type="Desktop CPU",
        transistor_count=54300000,
        manufacturer="AMD",
    ),
    Product(
        name="AMD K8 (64-bit, large cache)",
        year=2003,
        product_type="Desktop CPU",
        transistor_count=105900000,
        manufacturer="AMD",
    ),
    Product(
        name="Pentium M Banias (32-bit)",
        year=2003,
        product_type="Laptop CPU",
        transistor_count=77000000,
        manufacturer="Intel",
    ),
    Product(
        name="Itanium 2 Madison 6M (64-bit)",
        year=2003,
        product_type="Server CPU",
        transistor_count=410000000,
        manufacturer="Intel",
    ),
    Product(
        name="PlayStation 2 single chip (CPU + GPU)",
        year=2003,
        product_type="Mobile CPU",
        transistor_count=53500000,
        manufacturer="Sony, Toshiba",
    ),
    Product(
        name="Pentium 4 Prescott (32-bit, large cache)",
        year=2004,
        product_type="Desktop CPU",
        transistor_count=112000000,
        manufacturer="Intel",
    ),
    Product(
        name="Pentium M Dothan (32-bit)",
        year=2004,
        product_type="Laptop CPU",
        transistor_count=144000000,
        manufacturer="Intel",
    ),
    Product(
        name="SPARC64 V+ (64-bit, large cache)",
        year=2004,
        product_type="Server CPU",
        transistor_count=400000000,
        manufacturer="Fujitsu",
    ),
    Product(
        name="Itanium 2",  # (64-bit;9 MB cache)",
        year=2004,
        product_type="Server CPU",
        transistor_count=592000000,
        manufacturer="Intel",
        show=True,
    ),
    Product(
        name="Pentium 4 Prescott-2M (32-bit, large cache)",
        year=2005,
        product_type="Desktop CPU",
        transistor_count=169000000,
        manufacturer="Intel",
    ),
    Product(
        name="Pentium D Smithfield (64-bit, large cache)",
        year=2005,
        product_type="Desktop CPU",
        transistor_count=228000000,
        manufacturer="Intel",
    ),
    Product(
        name="Xenon (64-bit, 128-bit SIMD, large cache)",
        year=2005,
        product_type="Mobile CPU",
        transistor_count=165000000,
        manufacturer="IBM",
    ),
    Product(
        name="Cell (32-bit, cache)",
        year=2005,
        product_type="Mobile CPU",
        transistor_count=250000000,
        manufacturer="Sony, IBM, Toshiba",
    ),
    Product(
        name="Pentium 4 Cedar Mill (32-bit, large cache)",
        year=2006,
        product_type="Desktop CPU",
        transistor_count=184000000,
        manufacturer="Intel",
    ),
    Product(
        name="Pentium D Presler (64-bit, large cache)",
        year=2006,
        product_type="Desktop CPU",
        transistor_count=362000000,
        manufacturer="Intel",
    ),
    Product(
        name="Core 2 Duo Conroe (dual-core 64-bit, large caches)",
        year=2006,
        product_type="Desktop CPU",
        transistor_count=291000000,
        manufacturer="Intel",
    ),
    Product(
        name="Dual-core Itanium 2 (64-bit, SIMD, large caches)",
        year=2006,
        product_type="Server CPU",
        transistor_count=1700000000,
        manufacturer="Intel",
    ),
    Product(
        name="AMD K10 quad-core 2M L3 (64-bit, large caches)",
        year=2007,
        product_type="Desktop CPU",
        transistor_count=463000000,
        manufacturer="AMD",
    ),
    Product(
        name="ARM Cortex-A9 (32-bit, (optional) SIMD, caches)",
        year=2007,
        product_type="Mobile CPU",
        transistor_count=26000000,
        manufacturer="ARM",
    ),
    Product(
        name="Core 2 Duo Wolfdale (dual-core 64-bit, SIMD, caches)",
        year=2007,
        product_type="Desktop CPU",
        transistor_count=411000000,
        manufacturer="Intel",
    ),
    Product(
        name="POWER6 (64-bit, large caches)",
        year=2007,
        product_type="Server CPU",
        transistor_count=789000000,
        manufacturer="IBM",
    ),
    Product(
        name="Core 2 Duo Allendale (dual-core 64-bit, SIMD, large caches)",
        year=2007,
        product_type="Desktop CPU",
        transistor_count=169000000,
        manufacturer="Intel",
    ),
    Product(
        name="Uniphier",
        year=2007,
        product_type="Mobile CPU",
        transistor_count=250000000,
        manufacturer="Matsushita",
    ),
    Product(
        name="SPARC64 VI (64-bit, SIMD, large caches)",
        year=2007,
        product_type="Server CPU",
        transistor_count=540000000,
        manufacturer="Fujitsu",
    ),
    Product(
        name="Core 2 Duo Wolfdale 3M (dual-core 64-bit, SIMD, large caches)",
        year=2008,
        product_type="Desktop CPU",
        transistor_count=230000000,
        manufacturer="Intel",
    ),
    Product(
        name="Core i7",
        year=2008,
        product_type="Desktop CPU",
        transistor_count=731000000,
        manufacturer="Intel",
        show=True,
    ),
    Product(
        name="AMD K10 quad-core 6M L3 (64-bit, SIMD, large caches)",
        year=2008,
        product_type="Desktop CPU",
        transistor_count=758000000,
        manufacturer="AMD",
    ),
    Product(
        name="Atom (32-bit, large cache)",
        year=2008,
        product_type="Mobile CPU",
        transistor_count=47000000,
        manufacturer="Intel",
    ),
    Product(
        name="SPARC64 VII (64-bit, SIMD, large caches)",
        year=2008,
        product_type="Server CPU",
        transistor_count=600000000,
        manufacturer="Fujitsu",
    ),
    Product(
        name="Six-core Xeon 7400 (64-bit, SIMD, large caches)",
        year=2008,
        product_type="Server CPU",
        transistor_count=1900000000,
        manufacturer="Intel",
    ),
    Product(
        name="Six-core Opteron 2400 (64-bit, SIMD, large caches)",
        year=2009,
        product_type="Server CPU",
        transistor_count=904000000,
        manufacturer="AMD",
    ),
    Product(
        name="SPARC64 VIIIfx (64-bit, SIMD, large caches)",
        year=2009,
        product_type="Server CPU",
        transistor_count=760000000,
        manufacturer="Fujitsu",
    ),
    Product(
        name="Atom (Pineview) 64-bit, 1-core, 512 kB L2 cache",
        year=2010,
        product_type="Mobile CPU",
        transistor_count=123000000,
        manufacturer="Intel",
    ),
    Product(
        name="Atom (Pineview) 64-bit, 2-core, 1 MB L2 cache",
        year=2010,
        product_type="Mobile CPU",
        transistor_count=176000000,
        manufacturer="Intel",
    ),
    Product(
        name="SPARC T3 (16-core 64-bit, SIMD, large caches)",
        year=2010,
        product_type="Server CPU",
        transistor_count=1000000000,
        manufacturer="Sun / Oracle",
    ),
    Product(
        name="Six-core Core i7 (Gulftown)",
        year=2010,
        product_type="Desktop CPU",
        transistor_count=1170000000,
        manufacturer="Intel",
    ),
    Product(
        name="POWER7 32M L3 (8-core 64-bit, SIMD, large caches)",
        year=2010,
        product_type="Server CPU",
        transistor_count=1200000000,
        manufacturer="IBM",
    ),
    Product(
        name="Quad-core z196 (64-bit, very large caches)",
        year=2010,
        product_type="Server CPU",
        transistor_count=1400000000,
        manufacturer="IBM",
    ),
    Product(
        name="Quad-core Itanium Tukwila (64-bit, SIMD, large caches)",
        year=2010,
        product_type="Server CPU",
        transistor_count=2000000000,
        manufacturer="Intel",
    ),
    Product(
        name="Xeon Nehalem-EX (8-core 64-bit, SIMD, large caches)",
        year=2010,
        product_type="Server CPU",
        transistor_count=2300000000,
        manufacturer="Intel",
    ),
    Product(
        name="SPARC64 IXfx (64-bit, SIMD, large caches)",
        year=2011,
        product_type="Server CPU",
        transistor_count=1870000000,
        manufacturer="Fujitsu",
    ),
    Product(
        name="Quad-core + GPU Core i7 (64-bit, SIMD, large caches)",
        year=2011,
        product_type="Desktop CPU",
        transistor_count=1160000000,
        manufacturer="Intel",
    ),
    Product(
        name="Six-core Core i7/8-core Xeon E5 (Sandy Bridge-E/EP) (64-bit, SIMD, large caches)",
        year=2011,
        product_type="Server CPU",
        transistor_count=2270000000,
        manufacturer="Intel",
    ),
    Product(
        name="Xeon Westmere-EX (10-core 64-bit, SIMD, large caches)",
        year=2011,
        product_type="Server CPU",
        transistor_count=2600000000,
        manufacturer="Intel",
    ),
    Product(
        name='Atom "Medfield" (64-bit)',
        year=2012,
        product_type="Mobile CPU",
        transistor_count=432000000,
        manufacturer="Intel",
    ),
    Product(
        name="SPARC64 X (64-bit, SIMD, caches)",
        year=2012,
        product_type="Server CPU",
        transistor_count=2990000000,
        manufacturer="Fujitsu",
    ),
    Product(
        name="AMD Bulldozer (8-core 64-bit, SIMD, caches)",
        year=2012,
        product_type="Desktop CPU",
        transistor_count=1200000000,
        manufacturer="AMD",
    ),
    Product(
        name="Quad-core + GPU AMD Trinity (64-bit, SIMD, caches)",
        year=2012,
        product_type="Laptop CPU",
        transistor_count=1303000000,
        manufacturer="AMD",
    ),
    Product(
        name="Quad-core + GPU Core i7 Ivy Bridge (64-bit, SIMD, caches)",
        year=2012,
        product_type="Desktop CPU",
        transistor_count=1400000000,
        manufacturer="Intel",
    ),
    Product(
        name="POWER7+ (8-core 64-bit, SIMD, 80 MB L3 cache)",
        year=2012,
        product_type="Server CPU",
        transistor_count=2100000000,
        manufacturer="IBM",
    ),
    Product(
        name="Six-core zEC12 (64-bit, SIMD, large caches)",
        year=2012,
        product_type="Server CPU",
        transistor_count=2750000000,
        manufacturer="IBM",
    ),
    Product(
        name="Itanium Poulson (8-core 64-bit, SIMD, caches)",
        year=2012,
        product_type="Server CPU",
        transistor_count=3100000000,
        manufacturer="Intel",
    ),
    Product(
        name="Xeon Phi (61-core 32-bit, 512-bit SIMD, caches)",
        year=2012,
        product_type="Server CPU",
        transistor_count=5000000000,
        manufacturer="Intel",
    ),
    Product(
        name='Apple A7 (dual-core 64/32-bit ARM64, "mobile SoC", SIMD, caches)',
        year=2013,
        product_type="Mobile CPU",
        transistor_count=1000000000,
        manufacturer="Apple",
    ),
    Product(
        name="Six-core Core i7 Ivy Bridge E (64-bit, SIMD, caches)",
        year=2013,
        product_type="Desktop CPU",
        transistor_count=1860000000,
        manufacturer="Intel",
    ),
    Product(
        name="POWER8 (12-core 64-bit, SIMD, caches)",
        year=2013,
        product_type="Server CPU",
        transistor_count=4200000000,
        manufacturer="IBM",
    ),
    Product(
        name="Xbox One main SoC (64-bit, SIMD, caches)",
        year=2013,
        product_type="Mobile CPU",
        transistor_count=5000000000,
        manufacturer="Microsoft, AMD",
    ),
    Product(
        name="Quad-core + GPU Core i7 Haswell (64-bit, SIMD, caches)",
        year=2014,
        product_type="Desktop CPU",
        transistor_count=1400000000,
        manufacturer="Intel",
    ),
    Product(
        name='Apple A8 (dual-core 64/32-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2014,
        product_type="Mobile CPU",
        transistor_count=2000000000,
        manufacturer="Apple",
    ),
    Product(
        name="Core i7 Haswell-E (8-core 64-bit, SIMD, caches)",
        year=2014,
        product_type="Desktop CPU",
        transistor_count=2600000000,
        manufacturer="Intel",
    ),
    Product(
        name='Apple A8X (tri-core 64/32-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2014,
        product_type="Mobile CPU",
        transistor_count=3000000000,
        manufacturer="Apple",
    ),
    Product(
        name="Xeon Ivy Bridge-EX (15-core 64-bit, SIMD, caches)",
        year=2014,
        product_type="Server CPU",
        transistor_count=4310000000,
        manufacturer="Intel",
    ),
    Product(
        name="Xeon Haswell-E5 (18-core 64-bit, SIMD, caches)",
        year=2014,
        product_type="Server CPU",
        transistor_count=5560000000,
        manufacturer="Intel",
    ),
    Product(
        name="Quad-core + GPU GT2 Core i7 Skylake K (64-bit, SIMD, caches)",
        year=2015,
        product_type="Desktop CPU",
        transistor_count=1750000000,
        manufacturer="Intel",
    ),
    Product(
        name="Dual-core + GPU Iris Core i7 Broadwell-U (64-bit, SIMD, caches)",
        year=2015,
        product_type="Laptop CPU",
        transistor_count=1900000000,
        manufacturer="Intel",
    ),
    Product(
        name="A9",  #'Apple A9 (dual-core 64/32-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2015,
        product_type="Mobile CPU",
        transistor_count=2000000000,
        manufacturer="Apple",
        show=False,
    ),  # Row 1 of 2 for Apple A9
    Product(
        name='Apple A9 (dual-core 64/32-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2015,
        product_type="Mobile CPU",
        transistor_count=2000000000,
        manufacturer="Apple",
    ),  # Row 2 of 2 for Apple A9
    Product(
        name='Apple A9X (dual core 64/32-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2015,
        product_type="Mobile CPU",
        transistor_count=3000000000,
        manufacturer="Apple",
    ),
    Product(
        name="IBM z13 (64-bit, caches)",
        year=2015,
        product_type="Server CPU",
        transistor_count=3990000000,
        manufacturer="IBM",
    ),
    Product(
        name="IBM z13 Storage Controller",
        year=2015,
        product_type="Server CPU",
        transistor_count=7100000000,
        manufacturer="IBM",
    ),
    Product(
        name="SPARC M7 (32-core 64-bit, SIMD, caches)",
        year=2015,
        product_type="Server CPU",
        transistor_count=10000000000,
        manufacturer="Oracle",
    ),
    Product(
        name="Core i7 Broadwell-E (10-core 64-bit, SIMD, caches)",
        year=2016,
        product_type="Desktop CPU",
        transistor_count=3200000000,
        manufacturer="Intel",
    ),
    Product(
        name='Apple A10 Fusion (quad-core 64/32-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2016,
        product_type="Mobile CPU",
        transistor_count=3300000000,
        manufacturer="Apple",
    ),
    Product(
        name='HiSilicon Kirin 960 (octa-core 64/32-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2016,
        product_type="Mobile CPU",
        transistor_count=4000000000,
        manufacturer="Huawei",
    ),
    Product(
        name="Xeon Broadwell-E5 (22-core 64-bit, SIMD, caches)",
        year=2016,
        product_type="Server CPU",
        transistor_count=7200000000,
        manufacturer="Intel",
    ),
    Product(
        name="Xeon Phi (72-core 64-bit, 512-bit SIMD, caches)",
        year=2016,
        product_type="Server CPU",
        transistor_count=8000000000,
        manufacturer="Intel",
    ),
    Product(
        name="Zip CPU (32-bit, for FPGAs)",
        year=2016,
        product_type="Desktop CPU",
        transistor_count=0,
        manufacturer="Gisselquist Technology",
    ),
    Product(
        name='Qualcomm Snapdragon 835 (octa-core 64/32-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2016,
        product_type="Mobile CPU",
        transistor_count=3000000000,
        manufacturer="Qualcomm",
    ),
    Product(
        name='Apple A11 Bionic (hexa-core 64/32-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2017,
        product_type="Mobile CPU",
        transistor_count=4300000000,
        manufacturer="Apple",
    ),
    Product(
        name="AMD Zen CCX (core complex unit: 4 cores, 8 MB L3 cache)",
        year=2017,
        product_type="Desktop CPU",
        transistor_count=1400000000,
        manufacturer="AMD",
    ),
    Product(
        name="AMD Zeppelin SoC Ryzen (64-bit, SIMD, caches)",
        year=2017,
        product_type="Desktop CPU",
        transistor_count=4800000000,
        manufacturer="AMD",
    ),
    Product(
        name="AMD Ryzen 5 1600 Ryzen (64-bit, SIMD, caches)",
        year=2017,
        product_type="Desktop CPU",
        transistor_count=4800000000,
        manufacturer="AMD",
    ),
    Product(
        name="IBM z14 (64-bit, SIMD, caches)",
        year=2017,
        product_type="Server CPU",
        transistor_count=6100000000,
        manufacturer="IBM",
    ),
    Product(
        name="IBM z14 Storage Controller (64-bit)",
        year=2017,
        product_type="Server CPU",
        transistor_count=9700000000,
        manufacturer="IBM",
    ),
    Product(
        name='HiSilicon Kirin 970 (octa-core 64/32-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2017,
        product_type="Mobile CPU",
        transistor_count=5500000000,
        manufacturer="Huawei",
    ),
    Product(
        name="Xbox One X (Project Scorpio) main SoC (64-bit, SIMD, caches)",
        year=2017,
        product_type="Mobile CPU",
        transistor_count=7000000000,
        manufacturer="Microsoft, AMD",
    ),
    Product(
        name="Xeon Platinum 8180 (28-core 64-bit, SIMD, caches)",
        year=2017,
        product_type="Server CPU",
        transistor_count=8000000000,
        manufacturer="Intel",
    ),
    Product(
        name="Xeon (unspecified)",
        year=2017,
        product_type="Server CPU",
        transistor_count=7100000000,
        manufacturer="Intel",
    ),
    Product(
        name="POWER9 (64-bit, SIMD, caches)",
        year=2017,
        product_type="Server CPU",
        transistor_count=8000000000,
        manufacturer="IBM",
    ),
    Product(
        name="Freedom U500 Base Platform Chip (E51, 4×U54) RISC-V (64-bit, caches)",
        year=2017,
        product_type="Desktop CPU",
        transistor_count=250000000,
        manufacturer="SiFive",
    ),
    Product(
        name="SPARC64 XII (12-core 64-bit, SIMD, caches)",
        year=2017,
        product_type="Server CPU",
        transistor_count=5450000000,
        manufacturer="Fujitsu",
    ),
    Product(
        name='Apple A10X Fusion (hexa-core 64/32-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2017,
        product_type="Mobile CPU",
        transistor_count=4300000000,
        manufacturer="Apple",
    ),
    Product(
        name="Centriq 2400 (64/32-bit, SIMD, caches)",
        year=2017,
        product_type="Server CPU",
        transistor_count=18000000000,
        manufacturer="Qualcomm",
    ),
    Product(
        name="AMD Epyc (32-core 64-bit, SIMD, caches)",
        year=2017,
        product_type="Server CPU",
        transistor_count=19200000000,
        manufacturer="AMD",
    ),
    Product(
        name='Qualcomm Snapdragon 845 (octa-core 64/32-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2017,
        product_type="Mobile CPU",
        transistor_count=5300000000,
        manufacturer="Qualcomm",
    ),
    Product(
        name='Qualcomm Snapdragon 850 (octa-core 64/32-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2017,
        product_type="Laptop CPU",
        transistor_count=5300000000,
        manufacturer="Qualcomm",
    ),
    Product(
        name='HiSilicon Kirin 710 (octa-core ARM64 "mobile SoC", SIMD, caches)',
        year=2018,
        product_type="Mobile CPU",
        transistor_count=5500000000,
        manufacturer="Huawei",
    ),
    Product(
        name='Apple A12 Bionic (hexa-core ARM64 "mobile SoC", SIMD, caches)',
        year=2018,
        product_type="Mobile CPU",
        transistor_count=6900000000,
        manufacturer="Apple",
    ),
    Product(
        name='HiSilicon Kirin 980 (octa-core ARM64 "mobile SoC", SIMD, caches)',
        year=2018,
        product_type="Mobile CPU",
        transistor_count=6900000000,
        manufacturer="Huawei",
    ),
    Product(
        name='Qualcomm Snapdragon 8cx / SCX8180 (octa-core ARM64 "mobile SoC", SIMD, caches)',
        year=2018,
        product_type="Laptop CPU",
        transistor_count=8500000000,
        manufacturer="Qualcomm",
    ),
    Product(
        name='Apple A12X Bionic (octa-core 64/32-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2018,
        product_type="Mobile CPU",
        transistor_count=10000000000,
        manufacturer="Apple",
    ),
    Product(
        name="Fujitsu A64FX (64/32-bit, SIMD, caches)",
        year=2018,
        product_type="Server CPU",
        transistor_count=8786000000,
        manufacturer="Fujitsu",
    ),
    Product(
        name="Tegra Xavier SoC (64/32-bit)",
        year=2018,
        product_type="Mobile CPU",
        transistor_count=9000000000,
        manufacturer="Nvidia",
    ),
    Product(
        name='Qualcomm Snapdragon 855 (octa-core 64/32-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2018,
        product_type="Mobile CPU",
        transistor_count=6700000000,
        manufacturer="Qualcomm",
    ),
    Product(
        name="AMD Zen 2 core (0.5 MB L2 + 4 MB L3 cache)",
        year=2019,
        product_type="Desktop CPU",
        transistor_count=475000000,
        manufacturer="AMD",
    ),
    Product(
        name="AMD Zen 2 CCX (core complex: 4 cores, 16 MB L3 cache)",
        year=2019,
        product_type="Desktop CPU",
        transistor_count=1900000000,
        manufacturer="AMD",
    ),
    Product(
        name="AMD Zen 2 CCD (core complex die: 8 cores, 32 MB L3 cache)",
        year=2019,
        product_type="Desktop CPU",
        transistor_count=3800000000,
        manufacturer="AMD",
    ),
    Product(
        name="AMD Zen 2 client I/O die",
        year=2019,
        product_type="Desktop CPU",
        transistor_count=2090000000,
        manufacturer="AMD",
    ),
    Product(
        name="AMD Zen 2 server I/O die",
        year=2019,
        product_type="Server CPU",
        transistor_count=8340000000,
        manufacturer="AMD",
    ),
    Product(
        name="AMD Zen 2 Renoir die",
        year=2019,
        product_type="Laptop CPU",
        transistor_count=9800000000,
        manufacturer="AMD",
    ),
    Product(
        name="AMD Ryzen 7 3700X (64-bit, SIMD, caches, I/O die)",
        year=2019,
        product_type="Desktop CPU",
        transistor_count=5990000000,
        manufacturer="AMD",
    ),
    Product(
        name="HiSilicon Kirin 990 4G",
        year=2019,
        product_type="Mobile CPU",
        transistor_count=8000000000,
        manufacturer="Huawei",
    ),
    Product(
        name='Apple A13 (hexa-core 64-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2019,
        product_type="Mobile CPU",
        transistor_count=8500000000,
        manufacturer="Apple",
    ),
    Product(
        name="IBM z15 CP chip (12 cores, 256 MB L3 cache)",
        year=2019,
        product_type="Server CPU",
        transistor_count=9200000000,
        manufacturer="IBM",
    ),
    Product(
        name="IBM z15 SC chip (960 MB L4 cache)",
        year=2019,
        product_type="Server CPU",
        transistor_count=12200000000,
        manufacturer="IBM",
    ),
    Product(
        name="AMD Ryzen 9 3900X (64-bit, SIMD, caches, I/O die)",
        year=2019,
        product_type="Desktop CPU",
        transistor_count=9890000000,
        manufacturer="AMD",
    ),
    Product(
        name="HiSilicon Kirin 990 5G",
        year=2019,
        product_type="Mobile CPU",
        transistor_count=10300000000,
        manufacturer="Huawei",
    ),
    Product(
        name="AWS Graviton2 (64-bit, 64-core ARM-based, SIMD, caches)",
        year=2019,
        product_type="Server CPU",
        transistor_count=30000000000,
        manufacturer="Amazon",
    ),
    Product(
        name="AMD Epyc Rome (64-bit, SIMD, caches)",
        year=2019,
        product_type="Server CPU",
        transistor_count=39540000000,
        manufacturer="AMD",
    ),
    Product(
        name='Qualcomm Snapdragon 865 (octa-core 64/32-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2019,
        product_type="Mobile CPU",
        transistor_count=10300000000,
        manufacturer="Qualcomm",
    ),
    Product(
        name="TI Jacinto TDA4VM (ARM A72, DSP, SRAM)",
        year=2020,
        product_type="Mobile CPU",
        transistor_count=3500000000,
        manufacturer="Texas Instruments",
    ),
    Product(
        name='Apple A14 Bionic (hexa-core 64-bit ARM64 "mobile SoC", SIMD, caches)',
        year=2020,
        product_type="Mobile CPU",
        transistor_count=11800000000,
        manufacturer="Apple",
    ),
    Product(
        name="M1",  # "Apple M1",
        year=2020,
        product_type="Laptop CPU",
        transistor_count=16000000000,
        manufacturer="Apple",
        show=True,
    ),
    Product(
        name="HiSilicon Kirin 9000",
        year=2020,
        product_type="Mobile CPU",
        transistor_count=15300000000,
        manufacturer="Huawei",
    ),
    Product(
        name="AMD Zen 3 CCX (core complex unit: 8 cores, 32 MB L3 cache)",
        year=2020,
        product_type="Desktop CPU",
        transistor_count=4080000000,
        manufacturer="AMD",
    ),
    Product(
        name="AMD Zen 3 CCD (core complex die)",
        year=2020,
        product_type="Desktop CPU",
        transistor_count=4150000000,
        manufacturer="AMD",
    ),
    Product(
        name="Core 11th gen Rocket Lake (8-core 64-bit, SIMD, large caches)",
        year=2021,
        product_type="Desktop CPU",
        transistor_count=6000000000,
        manufacturer="Intel",
    ),
    Product(
        name="AMD Ryzen 7 5800H (64-bit, SIMD, caches, I/O and GPU)",
        year=2021,
        product_type="Laptop CPU",
        transistor_count=10700000000,
        manufacturer="AMD",
    ),
    Product(
        name="AMD Epyc 7763 (Milan) (64-core, 64-bit)",
        year=2021,
        product_type="Server CPU",
        transistor_count=0,
        manufacturer="AMD",
    ),
    Product(
        name="Apple A15",
        year=2021,
        product_type="Mobile CPU",
        transistor_count=15000000000,
        manufacturer="Apple",
    ),
    Product(
        name="Apple M1 Pro (10-core, 64-bit)",
        year=2021,
        product_type="Laptop CPU",
        transistor_count=33700000000,
        manufacturer="Apple",
    ),
    Product(
        name="Apple M1 Max (10-core, 64-bit)",
        year=2021,
        product_type="Laptop CPU",
        transistor_count=57000000000,
        manufacturer="Apple",
    ),
    Product(
        name="Power10 dual-chip module (30 SMT8 cores or 60 SMT4 cores)",
        year=2021,
        product_type="Server CPU",
        transistor_count=36000000000,
        manufacturer="IBM",
    ),
    Product(
        name="Dimensity 9000 (ARM64 SoC)",
        year=2021,
        product_type="Mobile CPU",
        transistor_count=15300000000,
        manufacturer="Mediatek",
    ),
    Product(
        name="Apple A16 (ARM64 SoC)",
        year=2022,
        product_type="Mobile CPU",
        transistor_count=16000000000,
        manufacturer="Apple",
    ),
    Product(
        name="Apple M1 Ultra (dual-chip module, 2×10 cores)",
        year=2022,
        product_type="Desktop CPU",
        transistor_count=114000000000,
        manufacturer="Apple",
    ),
    Product(
        name="AMD Epyc 7773X (Milan-X) (multi-chip module, 64 cores, 768 MB L3 cache)",
        year=2022,
        product_type="Server CPU",
        transistor_count=26000000000,
        manufacturer="AMD",
    ),
    Product(
        name="IBM Telum dual-chip module (2×8 cores, 2×256 MB cache)",
        year=2022,
        product_type="Server CPU",
        transistor_count=45000000000,
        manufacturer="IBM",
    ),
    Product(
        name="Apple M2 (deca-core 64-bit ARM64 SoC, SIMD, caches)",
        year=2022,
        product_type="Laptop CPU",
        transistor_count=20000000000,
        manufacturer="Apple",
    ),
    Product(
        name="Dimensity 9200 (ARM64 SoC)",
        year=2022,
        product_type="Mobile CPU",
        transistor_count=17000000000,
        manufacturer="Mediatek",
    ),
    Product(
        name='Qualcomm Snapdragon 8 Gen 2 (octa-core ARM64 "mobile SoC", SIMD, caches)',
        year=2022,
        product_type="Mobile CPU",
        transistor_count=16000000000,
        manufacturer="Qualcomm",
    ),
    Product(
        name="AMD EPYC Genoa (4th gen/9004 series) 13-chip module (up to 96 cores and 384 MB (L3) + 96 MB (L2) cache)",
        year=2022,
        product_type="Server CPU",
        transistor_count=90000000000,
        manufacturer="AMD",
    ),
    Product(
        name="HiSilicon Kirin 9000s",
        year=2023,
        product_type="Mobile CPU",
        transistor_count=9510000000,
        manufacturer="Huawei",
    ),
    Product(
        name="Apple M4 (deca-core 64-bit ARM64 SoC, SIMD, caches)",
        year=2024,
        product_type="Laptop CPU",
        transistor_count=28000000000,
        manufacturer="Apple",
    ),
    Product(
        name="Apple M3 (octa-core 64-bit ARM64 SoC, SIMD, caches)",
        year=2023,
        product_type="Laptop CPU",
        transistor_count=25000000000,
        manufacturer="Apple",
    ),
    Product(
        name="Apple M3 Pro (dodeca-core 64-bit ARM64 SoC, SIMD, caches)",
        year=2023,
        product_type="Laptop CPU",
        transistor_count=37000000000,
        manufacturer="Apple",
    ),
    Product(
        name="M3 Max",  # (16-core 64-bit ARM64 SoC, SIMD, caches)",
        year=2023,
        product_type="Laptop CPU",
        transistor_count=92000000000,
        manufacturer="Apple",
        show=True,
    ),
    Product(
        name="Apple A17",
        year=2023,
        product_type="Mobile CPU",
        transistor_count=19000000000,
        manufacturer="Apple",
    ),
    Product(
        name="Sapphire Rapids quad-chip module (up to 60 cores and 112.5 MB of cache)",
        year=2023,
        product_type="Server CPU",
        transistor_count=44000000000,
        manufacturer="Intel",
    ),
    Product(
        name="Apple M2 Pro (12-core 64-bit ARM64 SoC, SIMD, caches)",
        year=2023,
        product_type="Laptop CPU",
        transistor_count=40000000000,
        manufacturer="Apple",
    ),
    Product(
        name="Apple M2 Max (12-core 64-bit ARM64 SoC, SIMD, caches)",
        year=2023,
        product_type="Laptop CPU",
        transistor_count=67000000000,
        manufacturer="Apple",
    ),
    Product(
        name="Apple M2 Ultra (two M2 Max dies)",
        year=2023,
        product_type="Desktop CPU",
        transistor_count=134000000000,
        manufacturer="Apple",
    ),
    Product(
        name="AMD Epyc Bergamo (4th gen/97X4 series) 9-chip module (up to 128 cores and 256 MB (L3) + 128 MB (L2) cache)",
        year=2023,
        product_type="Server CPU",
        transistor_count=82000000000,
        manufacturer="AMD",
    ),
    Product(
        name="MI300A",  # "AMD Instinct MI300A",  # (multi-chip module, 24 cores, 128 GB GPU memory + 256 MB (LLC/L3) cache)",
        year=2023,
        product_type="Discrete GPU",
        transistor_count=146000000000,
        manufacturer="AMD",
        show=False,
    ),
    Product(
        name="M3 Ultra",
        year=2025,
        product_type="Desktop CPU",
        transistor_count=184_000_000_000,
        manufacturer="Apple",
        show=True,
        dx=30,
    ),
    # GPUs
    #
    #
    #
    Product(
        name="μPD7220 GDC",
        year=1982,
        product_type="Discrete GPU",
        transistor_count=40000,
        manufacturer="NEC",
    ),
    Product(
        name="ARTC HD63484",
        year=1984,
        product_type="Discrete GPU",
        transistor_count=60000,
        manufacturer="Hitachi",
    ),
    Product(
        name="CBM Agnus",
        year=1985,
        product_type="Discrete GPU",
        transistor_count=21000,
        manufacturer="Commodore",
    ),
    Product(
        name="YM7101 VDP",
        year=1988,
        product_type="Discrete GPU",
        transistor_count=100000,
        manufacturer="Yamaha, Sega",
    ),
    Product(
        name="Tom & Jerry",
        year=1993,
        product_type="Discrete GPU",
        transistor_count=750000,
        manufacturer="Flare",
    ),
    Product(
        name="VDP1",
        year=1994,
        product_type="Discrete GPU",
        transistor_count=1000000,
        manufacturer="Sega",
    ),
    Product(
        name="Sony GPU",
        year=1994,
        product_type="Discrete GPU",
        transistor_count=1000000,
        manufacturer="Toshiba",
    ),
    Product(
        name="NV1",
        year=1995,
        product_type="Discrete GPU",
        transistor_count=1000000,
        manufacturer="Nvidia, Sega",
    ),
    Product(
        name="Reality Coprocessor",
        year=1996,
        product_type="Discrete GPU",
        transistor_count=2600000,
        manufacturer="SGI",
    ),
    Product(
        name="PowerVR",
        year=1996,
        product_type="Discrete GPU",
        transistor_count=1200000,
        manufacturer="VideoLogic",
    ),
    Product(
        name="Voodoo Graphics",
        year=1996,
        product_type="Discrete GPU",
        transistor_count=1000000,
        manufacturer="3dfx",
    ),
    Product(
        name="Voodoo Rush",
        year=1997,
        product_type="Discrete GPU",
        transistor_count=1000000,
        manufacturer="3dfx",
    ),
    Product(
        name="NV3",
        year=1997,
        product_type="Discrete GPU",
        transistor_count=3500000,
        manufacturer="Nvidia",
    ),
    Product(
        name="i740",
        year=1998,
        product_type="Discrete GPU",
        transistor_count=3500000,
        manufacturer="Intel, Real3D",
    ),
    Product(
        name="Voodoo 2",
        year=1998,
        product_type="Discrete GPU",
        transistor_count=4000000,
        manufacturer="3dfx",
    ),
    Product(
        name="Voodoo Rush",
        year=1998,
        product_type="Discrete GPU",
        transistor_count=4000000,
        manufacturer="3dfx",
    ),  # This is the second Voodoo Rush, distinct from the 1997 one in the table
    Product(
        name="NV4",
        year=1998,
        product_type="Discrete GPU",
        transistor_count=7000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="PowerVR2 CLX2",
        year=1998,
        product_type="Discrete GPU",
        transistor_count=10000000,
        manufacturer="VideoLogic",
    ),
    Product(
        name="PowerVR2 PMX1",
        year=1999,
        product_type="Discrete GPU",
        transistor_count=6000000,
        manufacturer="VideoLogic",
    ),
    Product(
        name="Rage 128",
        year=1999,
        product_type="Discrete GPU",
        transistor_count=8000000,
        manufacturer="ATI",
    ),
    Product(
        name="Voodoo 3",
        year=1999,
        product_type="Discrete GPU",
        transistor_count=8100000,
        manufacturer="3dfx",
    ),
    Product(
        name="Graphics Synthesizer",
        year=1999,
        product_type="Discrete GPU",
        transistor_count=43000000,
        manufacturer="Sony, Toshiba",
    ),
    Product(
        name="NV5",
        year=1999,
        product_type="Discrete GPU",
        transistor_count=15000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="NV10",
        year=1999,
        product_type="Discrete GPU",
        transistor_count=17000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="NV11",
        year=2000,
        product_type="Discrete GPU",
        transistor_count=20000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="NV15",
        year=2000,
        product_type="Discrete GPU",
        transistor_count=25000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="Voodoo 4",
        year=2000,
        product_type="Discrete GPU",
        transistor_count=14000000,
        manufacturer="3dfx",
    ),
    Product(
        name="Voodoo 5",
        year=2000,
        product_type="Discrete GPU",
        transistor_count=28000000,
        manufacturer="3dfx",
    ),
    Product(
        name="R100",
        year=2000,
        product_type="Discrete GPU",
        transistor_count=30000000,
        manufacturer="ATI",
    ),
    Product(
        name="Flipper",
        year=2000,
        product_type="Discrete GPU",
        transistor_count=51000000,
        manufacturer="ArtX",
    ),
    Product(
        name="PowerVR3 KYRO",
        year=2001,
        product_type="Discrete GPU",
        transistor_count=14000000,
        manufacturer="Imagination",
    ),
    Product(
        name="PowerVR3 KYRO II",
        year=2001,
        product_type="Discrete GPU",
        transistor_count=15000000,
        manufacturer="Imagination",
    ),
    Product(
        name="NV2A",
        year=2001,
        product_type="Discrete GPU",
        transistor_count=60000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="NV20",
        year=2001,
        product_type="Discrete GPU",
        transistor_count=57000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="NV25",
        year=2002,
        product_type="Discrete GPU",
        transistor_count=63000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="NV28",
        year=2002,
        product_type="Discrete GPU",
        transistor_count=36000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="NV17/18",
        year=2002,
        product_type="Discrete GPU",
        transistor_count=29000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="R200",
        year=2001,
        product_type="Discrete GPU",
        transistor_count=60000000,
        manufacturer="ATI",
    ),
    Product(
        name="R300",
        year=2002,
        product_type="Discrete GPU",
        transistor_count=107000000,
        manufacturer="ATI",
    ),
    Product(
        name="R360",
        year=2003,
        product_type="Discrete GPU",
        transistor_count=117000000,
        manufacturer="ATI",
    ),
    Product(
        name="NV34",
        year=2003,
        product_type="Discrete GPU",
        transistor_count=45000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="NV34b",
        year=2004,
        product_type="Discrete GPU",
        transistor_count=45000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="NV30",
        year=2003,
        product_type="Discrete GPU",
        transistor_count=125000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="NV31",
        year=2003,
        product_type="Discrete GPU",
        transistor_count=80000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="NV35/38",
        year=2003,
        product_type="Discrete GPU",
        transistor_count=135000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="NV36",
        year=2003,
        product_type="Discrete GPU",
        transistor_count=82000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="R480",
        year=2004,
        product_type="Discrete GPU",
        transistor_count=160000000,
        manufacturer="ATI",
    ),
    Product(
        name="NV40",
        year=2004,
        product_type="Discrete GPU",
        transistor_count=222000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="NV44",
        year=2004,
        product_type="Discrete GPU",
        transistor_count=75000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="NV41",
        year=2005,
        product_type="Discrete GPU",
        transistor_count=222000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="NV42",
        year=2005,
        product_type="Discrete GPU",
        transistor_count=198000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="NV43",
        year=2005,
        product_type="Discrete GPU",
        transistor_count=146000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="G70",
        year=2005,
        product_type="Discrete GPU",
        transistor_count=303000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="Xenos",
        year=2005,
        product_type="Discrete GPU",
        transistor_count=232000000,
        manufacturer="ATI",
    ),
    Product(
        name="RSX Reality Synthesizer",
        year=2005,
        product_type="Discrete GPU",
        transistor_count=300000000,
        manufacturer="Nvidia, Sony",
    ),
    Product(
        name="R520",
        year=2005,
        product_type="Discrete GPU",
        transistor_count=321000000,
        manufacturer="ATI",
    ),
    Product(
        name="RV530",
        year=2005,
        product_type="Discrete GPU",
        transistor_count=157000000,
        manufacturer="ATI",
    ),
    Product(
        name="RV515",
        year=2005,
        product_type="Discrete GPU",
        transistor_count=107000000,
        manufacturer="ATI",
    ),
    Product(
        name="R580",
        year=2006,
        product_type="Discrete GPU",
        transistor_count=384000000,
        manufacturer="ATI",
    ),
    Product(
        name="G71",
        year=2006,
        product_type="Discrete GPU",
        transistor_count=278000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="G72",
        year=2006,
        product_type="Discrete GPU",
        transistor_count=112000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="G73",
        year=2006,
        product_type="Discrete GPU",
        transistor_count=177000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="G80",
        year=2006,
        product_type="Discrete GPU",
        transistor_count=681000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="G86 Tesla",
        year=2007,
        product_type="Discrete GPU",
        transistor_count=210000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="G84 Tesla",
        year=2007,
        product_type="Discrete GPU",
        transistor_count=289000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="RV560",
        year=2006,
        product_type="Discrete GPU",
        transistor_count=330000000,
        manufacturer="ATI",
    ),
    Product(
        name="R600",
        year=2007,
        product_type="Discrete GPU",
        transistor_count=700000000,
        manufacturer="ATI",
    ),
    Product(
        name="RV610",
        year=2007,
        product_type="Discrete GPU",
        transistor_count=180000000,
        manufacturer="ATI",
    ),
    Product(
        name="RV630",
        year=2007,
        product_type="Discrete GPU",
        transistor_count=390000000,
        manufacturer="ATI",
    ),
    Product(
        name="G92",
        year=2007,
        product_type="Discrete GPU",
        transistor_count=754000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="G94 Tesla",
        year=2008,
        product_type="Discrete GPU",
        transistor_count=505000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="G96 Tesla",
        year=2008,
        product_type="Discrete GPU",
        transistor_count=314000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="G98 Tesla",
        year=2008,
        product_type="Discrete GPU",
        transistor_count=210000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GT200",
        year=2008,
        product_type="Discrete GPU",
        transistor_count=1400000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="RV620",
        year=2008,
        product_type="Discrete GPU",
        transistor_count=181000000,
        manufacturer="ATI",
    ),
    Product(
        name="RV635",
        year=2008,
        product_type="Discrete GPU",
        transistor_count=378000000,
        manufacturer="ATI",
    ),
    Product(
        name="RV710",
        year=2008,
        product_type="Discrete GPU",
        transistor_count=242000000,
        manufacturer="ATI",
    ),
    Product(
        name="RV730",
        year=2008,
        product_type="Discrete GPU",
        transistor_count=514000000,
        manufacturer="ATI",
    ),
    Product(
        name="RV670",
        year=2008,
        product_type="Discrete GPU",
        transistor_count=666000000,
        manufacturer="ATI",
    ),
    Product(
        name="RV770",
        year=2008,
        product_type="Discrete GPU",
        transistor_count=956000000,
        manufacturer="ATI",
    ),
    Product(
        name="RV790",
        year=2008,
        product_type="Discrete GPU",
        transistor_count=959000000,
        manufacturer="ATI",
    ),
    Product(
        name="G92b Tesla",
        year=2008,
        product_type="Discrete GPU",
        transistor_count=754000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="G94b Tesla",
        year=2008,
        product_type="Discrete GPU",
        transistor_count=505000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="G96b Tesla",
        year=2008,
        product_type="Discrete GPU",
        transistor_count=314000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GT200b Tesla",
        year=2008,
        product_type="Discrete GPU",
        transistor_count=1400000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GT218 Tesla",
        year=2009,
        product_type="Discrete GPU",
        transistor_count=260000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GT216 Tesla",
        year=2009,
        product_type="Discrete GPU",
        transistor_count=486000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GT215 Tesla",
        year=2009,
        product_type="Discrete GPU",
        transistor_count=727000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="RV740",
        year=2009,
        product_type="Discrete GPU",
        transistor_count=826000000,
        manufacturer="ATI",
    ),
    Product(
        name="Cypress RV870",
        year=2009,
        product_type="Discrete GPU",
        transistor_count=2154000000,
        manufacturer="ATI",
    ),
    Product(
        name="Juniper RV840",
        year=2009,
        product_type="Discrete GPU",
        transistor_count=1040000000,
        manufacturer="ATI",
    ),
    Product(
        name="Redwood RV830",
        year=2010,
        product_type="Discrete GPU",
        transistor_count=627000000,
        manufacturer="AMD (ATI)",
    ),
    Product(
        name="Cedar RV810",
        year=2010,
        product_type="Discrete GPU",
        transistor_count=292000000,
        manufacturer="AMD",
    ),
    Product(
        name="Cayman RV970",
        year=2010,
        product_type="Discrete GPU",
        transistor_count=2640000000,
        manufacturer="AMD",
    ),
    Product(
        name="Barts RV940",
        year=2010,
        product_type="Discrete GPU",
        transistor_count=1700000000,
        manufacturer="AMD",
    ),
    Product(
        name="Turks RV930",
        year=2011,
        product_type="Discrete GPU",
        transistor_count=716000000,
        manufacturer="AMD",
    ),
    Product(
        name="Caicos RV910",
        year=2011,
        product_type="Discrete GPU",
        transistor_count=370000000,
        manufacturer="AMD",
    ),
    Product(
        name="GF100 Fermi",
        year=2010,
        product_type="Discrete GPU",
        transistor_count=3200000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GF110 Fermi",
        year=2010,
        product_type="Discrete GPU",
        transistor_count=3000000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GF104 Fermi",
        year=2011,
        product_type="Discrete GPU",
        transistor_count=1950000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GF106 Fermi",
        year=2010,
        product_type="Discrete GPU",
        transistor_count=1170000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GF108 Fermi",
        year=2011,
        product_type="Discrete GPU",
        transistor_count=585000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GF119 Fermi",
        year=2011,
        product_type="Discrete GPU",
        transistor_count=292000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="Tahiti GCN1",
        year=2011,
        product_type="Discrete GPU",
        transistor_count=4312711873,
        manufacturer="AMD",
    ),
    Product(
        name="Cape Verde GCN1",
        year=2012,
        product_type="Discrete GPU",
        transistor_count=1500000000,
        manufacturer="AMD",
    ),
    Product(
        name="Pitcairn GCN1",
        year=2012,
        product_type="Discrete GPU",
        transistor_count=2800000000,
        manufacturer="AMD",
    ),
    Product(
        name="GK110 Kepler",
        year=2012,
        product_type="Discrete GPU",
        transistor_count=7080000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GK104 Kepler",
        year=2012,
        product_type="Discrete GPU",
        transistor_count=3540000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GK106 Kepler",
        year=2012,
        product_type="Discrete GPU",
        transistor_count=2540000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GK107 Kepler",
        year=2012,
        product_type="Discrete GPU",
        transistor_count=1270000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GK208 Kepler",
        year=2013,
        product_type="Discrete GPU",
        transistor_count=1020000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="Oland GCN1",
        year=2013,
        product_type="Discrete GPU",
        transistor_count=1040000000,
        manufacturer="AMD",
    ),
    Product(
        name="Bonaire GCN2",
        year=2013,
        product_type="Discrete GPU",
        transistor_count=2080000000,
        manufacturer="AMD",
    ),
    Product(
        name="Durango (Xbox One)",
        year=2013,
        product_type="Discrete GPU",
        transistor_count=4800000000,
        manufacturer="AMD",
    ),
    Product(
        name="Liverpool (PlayStation 4)",
        year=2013,
        product_type="Discrete GPU",
        transistor_count=0,
        manufacturer="AMD",
    ),  # ? becomes 0
    Product(
        name="Hawaii GCN2",
        year=2013,
        product_type="Discrete GPU",
        transistor_count=6300000000,
        manufacturer="AMD",
    ),
    Product(
        name="GM200 Maxwell",
        year=2015,
        product_type="Discrete GPU",
        transistor_count=8000000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GM204 Maxwell",
        year=2014,
        product_type="Discrete GPU",
        transistor_count=5200000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GM206 Maxwell",
        year=2014,
        product_type="Discrete GPU",
        transistor_count=2940000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GM107 Maxwell",
        year=2014,
        product_type="Discrete GPU",
        transistor_count=1870000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="Tonga GCN3",
        year=2014,
        product_type="Discrete GPU",
        transistor_count=5000000000,
        manufacturer="AMD",
    ),
    Product(
        name="Fiji GCN3",
        year=2015,
        product_type="Discrete GPU",
        transistor_count=8900000000,
        manufacturer="AMD",
    ),
    Product(
        name="Durango 2 (Xbox One S)",
        year=2016,
        product_type="Discrete GPU",
        transistor_count=5000000000,
        manufacturer="AMD",
    ),
    Product(
        name="Neo (PlayStation 4 Pro)",
        year=2016,
        product_type="Discrete GPU",
        transistor_count=5700000000,
        manufacturer="AMD",
    ),
    Product(
        name="Ellesmere/Polaris 10 GCN4",
        year=2016,
        product_type="Discrete GPU",
        transistor_count=5700000000,
        manufacturer="AMD",
    ),
    Product(
        name="Baffin/Polaris 11 GCN4",
        year=2016,
        product_type="Discrete GPU",
        transistor_count=3000000000,
        manufacturer="AMD",
    ),
    Product(
        name="Lexa/Polaris 12 GCN4",
        year=2017,
        product_type="Discrete GPU",
        transistor_count=2200000000,
        manufacturer="AMD",
    ),
    Product(
        name="GP100 Pascal",
        year=2016,
        product_type="Discrete GPU",
        transistor_count=15300000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GP102 Pascal",
        year=2016,
        product_type="Discrete GPU",
        transistor_count=11800000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GP104 Pascal",
        year=2016,
        product_type="Discrete GPU",
        transistor_count=7200000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GP106 Pascal",
        year=2016,
        product_type="Discrete GPU",
        transistor_count=4400000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GP107 Pascal",
        year=2016,
        product_type="Discrete GPU",
        transistor_count=3300000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GP108 Pascal",
        year=2017,
        product_type="Discrete GPU",
        transistor_count=1850000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="Scorpio (Xbox One X)",
        year=2017,
        product_type="Discrete GPU",
        transistor_count=6600000000,
        manufacturer="AMD",
    ),
    Product(
        name="Vega 10 GCN5",
        year=2017,
        product_type="Discrete GPU",
        transistor_count=12500000000,
        manufacturer="AMD",
    ),
    Product(
        name="GV100",  # Volta",
        year=2017,
        product_type="Discrete GPU",
        transistor_count=21100000000,
        manufacturer="Nvidia",
        show=True,
    ),
    Product(
        name="TU102 Turing",
        year=2018,
        product_type="Discrete GPU",
        transistor_count=18600000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="TU104 Turing",
        year=2018,
        product_type="Discrete GPU",
        transistor_count=13600000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="TU106 Turing",
        year=2018,
        product_type="Discrete GPU",
        transistor_count=10800000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="TU116 Turing",
        year=2019,
        product_type="Discrete GPU",
        transistor_count=6600000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="TU117 Turing",
        year=2019,
        product_type="Discrete GPU",
        transistor_count=4700000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="Vega 20 GCN5",
        year=2018,
        product_type="Discrete GPU",
        transistor_count=13230000000,
        manufacturer="AMD",
    ),
    Product(
        name="Navi 10 RDNA",
        year=2019,
        product_type="Discrete GPU",
        transistor_count=10300000000,
        manufacturer="AMD",
    ),
    Product(
        name="Navi 12 RDNA",
        year=2020,
        product_type="Discrete GPU",
        transistor_count=0,
        manufacturer="AMD",
    ),  # ? becomes 0
    Product(
        name="Navi 14 RDNA",
        year=2019,
        product_type="Discrete GPU",
        transistor_count=6400000000,
        manufacturer="AMD",
    ),
    Product(
        name="Arcturus CDNA",
        year=2020,
        product_type="Discrete GPU",
        transistor_count=25600000000,
        manufacturer="AMD",
    ),
    Product(
        name="GA100 Ampere",
        year=2020,
        product_type="Discrete GPU",
        transistor_count=54200000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GA102 Ampere",
        year=2020,
        product_type="Discrete GPU",
        transistor_count=28300000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GA103 Ampere",
        year=2022,
        product_type="Discrete GPU",
        transistor_count=22000000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GA104 Ampere",
        year=2020,
        product_type="Discrete GPU",
        transistor_count=17400000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GA106 Ampere",
        year=2021,
        product_type="Discrete GPU",
        transistor_count=12000000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="GA107 Ampere",
        year=2021,
        product_type="Discrete GPU",
        transistor_count=8700000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="Navi 21 RDNA2",
        year=2020,
        product_type="Discrete GPU",
        transistor_count=26800000000,
        manufacturer="AMD",
    ),
    Product(
        name="Navi 22 RDNA2",
        year=2021,
        product_type="Discrete GPU",
        transistor_count=17200000000,
        manufacturer="AMD",
    ),
    Product(
        name="Navi 23 RDNA2",
        year=2021,
        product_type="Discrete GPU",
        transistor_count=11060000000,
        manufacturer="AMD",
    ),
    Product(
        name="Navi 24 RDNA2",
        year=2022,
        product_type="Discrete GPU",
        transistor_count=5400000000,
        manufacturer="AMD",
    ),
    Product(
        name="Aldebaran CDNA2",
        year=2021,
        product_type="Discrete GPU",
        transistor_count=58200000000,
        manufacturer="AMD",
    ),  # Takes the first value before (MCM)
    Product(
        name="GH100",  # Hopper",
        year=2022,
        product_type="Discrete GPU",
        transistor_count=80000000000,
        manufacturer="Nvidia",
        show=False,
    ),
    Product(
        name="AD102 Ada Lovelace",
        year=2022,
        product_type="Discrete GPU",
        transistor_count=76300000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="AD103 Ada Lovelace",
        year=2022,
        product_type="Discrete GPU",
        transistor_count=45900000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="AD104 Ada Lovelace",
        year=2022,
        product_type="Discrete GPU",
        transistor_count=35800000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="AD106 Ada Lovelace",
        year=2023,
        product_type="Discrete GPU",
        transistor_count=0,
        manufacturer="Nvidia",
    ),  # ? becomes 0
    Product(
        name="AD107 Ada Lovelace",
        year=2023,
        product_type="Discrete GPU",
        transistor_count=0,
        manufacturer="Nvidia",
    ),  # ? becomes 0
    Product(
        name="Navi 31 RDNA3",
        year=2022,
        product_type="Discrete GPU",
        transistor_count=57700000000,
        manufacturer="AMD",
    ),  # Takes the first value before (MCM)
    Product(
        name="Navi 32 RDNA3",
        year=2023,
        product_type="Discrete GPU",
        transistor_count=28100000000,
        manufacturer="AMD",
    ),  # Takes the value before (MCM)
    Product(
        name="Navi 33 RDNA3",
        year=2023,
        product_type="Discrete GPU",
        transistor_count=13300000000,
        manufacturer="AMD",
    ),
    Product(
        name="Aqua Vanjaram CDNA3",
        year=2023,
        product_type="Discrete GPU",
        transistor_count=153000000000,
        manufacturer="AMD",
    ),  # Takes value before (MCM)
    Product(
        name="GB200",  # Grace Blackwell",
        year=2024,
        product_type="Discrete GPU",
        transistor_count=208000000000,
        manufacturer="Nvidia",
        show=True,
        dy=17,
        dx=10,
    ),  # Takes value before (MCM)
    Product(
        name="GB202 Blackwell (RTX 5090)",
        year=2025,
        product_type="Discrete GPU",
        transistor_count=92200000000,
        manufacturer="Nvidia",
    ),
    Product(
        name="Cell Broadband Engine",
        year=2006,
        product_type="Discrete GPU",
        transistor_count=250_000_000,
        manufacturer="IBM, Sony",
    ),
    Product(
        name="TPUv3",
        year=2018,
        product_type="AI Accelerator",
        transistor_count=10_000_000_000,  # https://people.csail.mit.edu/suvinay/pubs/2023.tpu.isca.pdf
        manufacturer="Google",
    ),
    Product(
        name="TPUv4",
        year=2021,
        product_type="AI Accelerator",
        transistor_count=22_000_000_000,  # https://people.csail.mit.edu/suvinay/pubs/2023.tpu.isca.pdf
        manufacturer="Google",
        show=True,
        dx=0,
        dy=30,
    ),  # other TPUs don't have publically available transistor counts
    Product(
        name="WSE-1",
        year=2019,
        product_type="AI Accelerator",
        transistor_count=1_200_000_000_000,
        manufacturer="Cerebras",
        show=True,
    ),
    Product(
        name="WSE-2",
        year=2020,
        product_type="AI Accelerator",
        transistor_count=2_600_000_000_000,
        manufacturer="Cerebras",
        show=True,
    ),
    Product(
        name="WSE-3",
        year=2024,
        product_type="AI Accelerator",
        transistor_count=4_000_000_000_000,
        manufacturer="Cerebras",
        show=True,
    ),
    Product(
        name="Dojo D1 Tile",
        year=2023,
        product_type="AI Accelerator",
        transistor_count=1_250_000_000_000,  # 50B transistors per D1 chip, 25 chips per tile
        manufacturer="Tesla",
        show=True,
        dx=6,
    ),
    Product(
        name="GC200 IPU",
        year=2020,
        product_type="AI Accelerator",
        transistor_count=59_000_000_000,
        manufacturer="Graphcore",
        show=False,
    ),
    Product(
        name="TSP v1",
        year=2020,
        product_type="AI Accelerator",
        transistor_count=26_800_000_000,
        manufacturer="Groq",
        show=False,
    ),
    Product(
        name="SN40L",
        year=2023,
        product_type="AI Accelerator",
        transistor_count=102_000_000_000,
        manufacturer="SambaNova",
        show=False,
    ),
    Product(
        name="Trainium v2",
        year=2023,
        product_type="AI Accelerator",
        transistor_count=58_000_000_000,
        manufacturer="Amazon",
        show=False,
    ),
    Product(
        name="Graviton v4",
        year=2023,
        product_type="Server CPU",
        transistor_count=73_000_000_000,
        manufacturer="Amazon",
        show=False,
    ),
    Product(
        name="Corsair C8",
        year=2023,
        product_type="AI Accelerator",
        transistor_count=130_000_000_000,
        manufacturer="D-Matrix",
        show=False,
    ),
]
