#!/usr/bin/env python

from livereload import Server, shell

if __name__ == "__main__":
    server = Server()
    # Base template
    server.watch('base/base.jinja2', shell('make'))
    server.watch('base/base.scss', shell('make'))

    # Poster template
    server.watch('templates/**/*.jinja2', shell('make'))
    server.watch('templates/**/*.scss', shell('make'))

    # Poster content
    server.watch('posters/**/*.jinja2', shell('make'))
    server.watch('figs/**/*.png')
    server.watch('figs/**/*.svg')
    server.serve()
